# Generated by Django 4.2.10 on 2026-05-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('bfs', 'Búsqueda en Amplitud (BFS)'), ('dfs', 'Búsqueda en Profundidad (DFS)'), ('ucs', 'Búsqueda con Costo Uniforme (UCS)')], max_length=3)),
                ('initial_state', models.TextField()),
                ('target_state', models.TextField()),
                ('result_path', models.TextField()),
                ('total_cost', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
